image: node:14.5-alpine

stages:
  - build
  - test
  # - deploy

cache:
  paths:
    - node_modules/

build-crush:
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  only:
    - merge_requests
  artifacts:
    paths:
      - node_modules/

test-crush:
  stage: test
  script:
    - chmod +x ./setup_env.sh
    - ./setup_env.sh
    - cat .env
    - npm test
  only:
    - merge_requests

# deploy-crush:
#   stage: deploy
#   script:
#     - echo comming soon
#   only:
#     - master