stages:
  - build
  - test
  # - push

services:
  - docker:dind

variables:
  API_IMAGE: registry.gitlab.com:5555/n19l/crush-api-user:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

cache:
  paths:
    - node_modules/

build-crush:
  image: node:14.5-alpine
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  only:
    - merge_requests
  artifacts:
    paths:
      - node_modules/

test-crush:
  image: node:14.5-alpine
  stage: test
  script:
    - chmod +x ./setup_env.sh
    - ./setup_env.sh
    - npm test
  only:
    - merge_requests

build-image-crush:
  image: docker:latest
  stage: build
  script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker build --pull -t $API_IMAGE .
    - docker push $API_IMAGE
  only:
    - master