stages:
  - build
  - test
  - push

cache:
  paths:
    - node_modules/

build-crush:
  image: node:14.5-alpine
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  only:
    - merge_requests
  artifacts:
    paths:
      - node_modules/

test-crush:
  image: node:14.5-alpine
  stage: test
  script:
    - chmod +x ./setup_env.sh
    - ./setup_env.sh
    - npm test
  only:
    - merge_requests

build-image-crush:
  image: docker:latest
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  services:
    - docker:dind
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
  only:
    - merge_requests

push-image-crush:
  image: docker:latest
  stage: push
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  services:
    - docker:dind
  script:
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - merge_requests