image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

build-crush:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - node_modules/

test-crush:
  stage: test
  script: npm test